#!/bin/bash
echo "AI Office Landing v2.3.0 - 安装验证"
echo ""
echo "✓ Skill 已安装到: ~/.claude/skills/ai-office-landing"
echo "✓ 版本: v2.3.0"
echo "✓ 核心组件:"
echo "  - orchestrator.sh (Phase 3.5 工作集成)"
echo "  - discover-skills.sh (动态 Skill 发现)"
echo "  - cost-tracker.sh (成本追踪)"
echo "✓ 快捷命令: /landing"
echo ""
echo "开始使用:"
echo "  claude"
echo "  /landing"
echo ""
